### ISSUE TITLE
Remove/Revoke AMO API credentials

### ISSUE THREAD

**Issue by wagnerand** [Jimgitsit/Code-Samples#1]
You should never share your AMO API credentials. Anyone that has them can upload new versions of your add-on on your behalf.

You need to:
- At the very least revoke the AMO API credentials on https://addons.mozilla.org/en-US/developers/addon/api/key/ _immediately_
- Remove the file or the credentials in it and never ever store it in a remote repository again.

**Comment by Jimgitsit** [comment]
Good catch. Thanks.
